#!/bin/bash

# Auto-Build Environment Setup for Columba
# Generated by Planner Agent for: Add Emoji Reactions Feature

set -e

echo "========================================"
echo "Columba Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_ROOT="/home/tyler/repos/public/columba"
cd "$PROJECT_ROOT"

# ============================================
# VERIFY ENVIRONMENT
# ============================================

echo ""
echo "Checking development environment..."

# Check Java
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | head -n 1)
    echo -e "${GREEN}✓ Java:${NC} $JAVA_VERSION"
else
    echo -e "${RED}✗ Java not found${NC}"
    exit 1
fi

# Check Gradle wrapper
if [ -f "./gradlew" ]; then
    echo -e "${GREEN}✓ Gradle wrapper present${NC}"
else
    echo -e "${RED}✗ Gradle wrapper not found${NC}"
    exit 1
fi

# Check Python
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version)
    echo -e "${GREEN}✓ Python:${NC} $PYTHON_VERSION"
else
    echo -e "${YELLOW}⚠ Python3 not found (needed for Python tests)${NC}"
fi

# ============================================
# RUN INITIAL BUILD CHECK
# ============================================

echo ""
echo "Running initial Kotlin compilation check..."

if ./gradlew :app:compileDebugKotlin --quiet 2>&1 | tail -3 | grep -q "BUILD SUCCESSFUL"; then
    echo -e "${GREEN}✓ Kotlin compilation successful${NC}"
else
    echo -e "${RED}✗ Kotlin compilation failed - check for errors${NC}"
    ./gradlew :app:compileDebugKotlin 2>&1 | tail -20
    exit 1
fi

# ============================================
# RUN LINTING CHECK
# ============================================

echo ""
echo "Running lint checks..."

if ./gradlew detekt ktlintCheck --quiet 2>&1 | tail -3 | grep -q "BUILD SUCCESSFUL"; then
    echo -e "${GREEN}✓ Lint checks passed${NC}"
else
    echo -e "${YELLOW}⚠ Lint checks have issues (can be fixed during implementation)${NC}"
fi

# ============================================
# RUN UNIT TESTS
# ============================================

echo ""
echo "Running existing unit tests..."

if ./gradlew :app:testDebugUnitTest --quiet 2>&1 | tail -3 | grep -q "BUILD SUCCESSFUL"; then
    echo -e "${GREEN}✓ All existing unit tests pass${NC}"
else
    echo -e "${RED}✗ Some unit tests failed${NC}"
    ./gradlew :app:testDebugUnitTest 2>&1 | tail -30
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Development!"
echo "========================================"
echo ""
echo "Quick Commands:"
echo "  Build:       ./gradlew :app:assembleDebug"
echo "  Test:        ./gradlew :app:testDebugUnitTest"
echo "  Lint:        ./gradlew detekt ktlintCheck"
echo "  Install:     ./build-debug.sh && ./install-debug.sh"
echo ""
echo "Key Files to Modify:"
echo "  - app/src/main/java/com/lxmf/messenger/ui/model/MessageUi.kt"
echo "  - app/src/main/java/com/lxmf/messenger/ui/model/MessageMapper.kt"
echo "  - app/src/main/java/com/lxmf/messenger/ui/screens/MessagingScreen.kt"
echo "  - app/src/main/java/com/lxmf/messenger/viewmodel/MessagingViewModel.kt"
echo ""
echo "Pattern Reference Files:"
echo "  - app/src/main/java/com/lxmf/messenger/ui/components/ReplyComponents.kt"
echo "  - python/reticulum_wrapper.py (lines 2811-2820 for Field 16)"
echo ""
