package network.columba.app.rns.backend.py

import network.columba.app.rns.api.model.InterfaceConfig
import network.columba.app.rns.api.model.LogLevel
import network.columba.app.rns.api.model.ReticulumConfig

/**
 * Renders a [ReticulumConfig] into upstream RNS's on-disk `config` file
 * format. Upstream `RNS.Reticulum(configdir=...)` reads `<configdir>/config`
 * at construction; this is how the Python flavor's interfaces get wired.
 *
 * This is **backend-specific marshalling**, not app logic — the kotlin
 * backend hands the same [ReticulumConfig] to reticulum-kt's typed API
 * instead. It lives here (not in `:rns-host`) because the RNS config-file
 * grammar is a Python-RNS concept.
 *
 * Coverage: the IP-based interface types (`AutoInterface`, `TCPClient`,
 * `TCPServer`, `UDP`) render to complete, correct sections. `RNode` and
 * `AndroidBLE` render a section pointing at the bundled custom interface
 * class — but those classes also have to be *deployed* into the RNS
 * interfaces directory for `Transport.find_interfaces()` to load them; that
 * deployment step is on-device integration work (see PINNED_VERSIONS.md).
 */
internal object RnsConfigFile {
    /**
     * Build the `config` file contents for [config].
     *
     * `shareInstance` true → render `share_instance = yes` and SKIP
     * the `[interfaces]` block so RNS RPCs into an existing shared
     * instance (mirrors v0.10.x). Otherwise render `[interfaces]` with
     * the user's enabled set; AutoInterface entries get force-disabled
     * (with a `# WARNING: ...` comment) when `skipAutoInterface = true`
     * — the caller has determined the multicast bind would conflict
     * with another RNS app on the device.
     */
    fun build(
        config: ReticulumConfig,
        shareInstance: Boolean = false,
        skipAutoInterface: Boolean = false,
    ): String {
        val sb = StringBuilder()
        sb.appendLine("# Generated by :rns-backend-py — do not hand-edit.")
        sb.appendLine()
        sb.appendLine("[reticulum]")
        sb.appendLine("  enable_transport = ${yesNo(config.enableTransport)}")
        sb.appendLine("  share_instance = ${yesNo(shareInstance)}")
        if (shareInstance) sb.appendLine("  shared_instance_type = tcp")
        sb.appendLine("  shared_instance_port = 37428")
        sb.appendLine("  instance_control_port = 37429")
        // Inter-app shared-instance auth (Sideband → Connectivity → Share
        // Instance Access). Only relevant when joining; harmless to omit
        // when we're the master, so gate on shareInstance.
        if (shareInstance) {
            config.rpcKey?.takeIf { it.isNotBlank() }?.let {
                sb.appendLine("  rpc_key = $it")
            }
        }
        sb.appendLine("  panic_on_interface_error = No")
        sb.appendLine()
        sb.appendLine("[logging]")
        sb.appendLine("  loglevel = ${logLevel(config.logLevel)}")
        if (!shareInstance) {
            sb.appendLine()
            sb.appendLine("[interfaces]")
            config.enabledInterfaces.filter { it.enabled }.forEach { iface ->
                renderInterface(sb, iface, skipAutoInterface)
            }
        }
        return sb.toString()
    }

    private fun renderInterface(
        sb: StringBuilder,
        iface: InterfaceConfig,
        skipAutoInterface: Boolean = false,
    ) {
        sb.appendLine()
        sb.appendLine("  [[${iface.name}]]")
        when (iface) {
            is InterfaceConfig.AutoInterface -> {
                if (skipAutoInterface) {
                    sb.appendLine("    # WARNING: AutoInterface disabled at runtime because another RNS")
                    sb.appendLine("    # app on this device holds the multicast data port. Enabling it")
                    sb.appendLine("    # would crash this process with EADDRINUSE.")
                    sb.appendLine("    type = AutoInterface")
                    sb.appendLine("    enabled = no")
                    return
                }
                sb.appendLine("    type = AutoInterface")
                sb.appendLine("    enabled = yes")
                if (iface.groupId.isNotBlank()) sb.appendLine("    group_id = ${iface.groupId}")
                sb.appendLine("    discovery_scope = ${iface.discoveryScope}")
                iface.discoveryPort?.let { sb.appendLine("    discovery_port = $it") }
                iface.dataPort?.let { sb.appendLine("    data_port = $it") }
                sb.appendLine("    mode = ${iface.mode}")
            }
            is InterfaceConfig.TCPClient -> {
                sb.appendLine("    type = TCPClientInterface")
                sb.appendLine("    enabled = yes")
                sb.appendLine("    target_host = ${iface.targetHost}")
                sb.appendLine("    target_port = ${iface.targetPort}")
                if (iface.kissFraming) sb.appendLine("    kiss_framing = true")
                sb.appendLine("    mode = ${iface.mode}")
                iface.networkName?.let { sb.appendLine("    network_name = $it") }
                iface.passphrase?.let { sb.appendLine("    passphrase = $it") }
            }
            is InterfaceConfig.TCPServer -> {
                sb.appendLine("    type = TCPServerInterface")
                sb.appendLine("    enabled = yes")
                sb.appendLine("    listen_ip = ${iface.listenIp}")
                sb.appendLine("    listen_port = ${iface.listenPort}")
                sb.appendLine("    mode = ${iface.mode}")
                iface.networkName?.let { sb.appendLine("    network_name = $it") }
                iface.passphrase?.let { sb.appendLine("    passphrase = $it") }
            }
            is InterfaceConfig.UDP -> {
                sb.appendLine("    type = UDPInterface")
                sb.appendLine("    enabled = yes")
                sb.appendLine("    listen_ip = ${iface.listenIp}")
                sb.appendLine("    listen_port = ${iface.listenPort}")
                sb.appendLine("    forward_ip = ${iface.forwardIp}")
                sb.appendLine("    forward_port = ${iface.forwardPort}")
                sb.appendLine("    mode = ${iface.mode}")
            }
            is InterfaceConfig.RNode -> {
                // The RNode interface ships as a bundled custom interface
                // (rnode_interface.py -> ColumbaRNodeInterface). It must be
                // deployed into the RNS interfaces directory before
                // Transport.find_interfaces() can load it — on-device work.
                sb.appendLine("    # RNode — bundled custom interface; needs interface-file deployment")
                sb.appendLine("    type = ColumbaRNodeInterface")
                sb.appendLine("    enabled = yes")
                sb.appendLine("    connection_mode = ${iface.connectionMode}")
                if (iface.targetDeviceName.isNotBlank()) {
                    sb.appendLine("    target_device_name = ${iface.targetDeviceName}")
                }
                iface.tcpHost?.let { sb.appendLine("    tcp_host = $it") }
                sb.appendLine("    tcp_port = ${iface.tcpPort}")
                iface.usbDeviceId?.let { sb.appendLine("    usb_device_id = $it") }
                sb.appendLine("    frequency = ${iface.frequency}")
                sb.appendLine("    bandwidth = ${iface.bandwidth}")
                sb.appendLine("    txpower = ${iface.txPower}")
                sb.appendLine("    spreadingfactor = ${iface.spreadingFactor}")
                sb.appendLine("    codingrate = ${iface.codingRate}")
                sb.appendLine("    mode = ${iface.mode}")
            }
            is InterfaceConfig.AndroidBLE -> {
                // Same as RNode: bundled custom interface (ble_modules/
                // android_ble_interface.py -> AndroidBLEInterface), needs
                // interface-file deployment. See PINNED_VERSIONS.md.
                sb.appendLine("    # AndroidBLE — bundled custom interface; needs interface-file deployment")
                sb.appendLine("    type = AndroidBLEInterface")
                sb.appendLine("    enabled = yes")
                sb.appendLine("    max_peers = ${iface.maxConnections}")
                sb.appendLine("    mode = ${iface.mode}")
                sb.appendLine("    ble_power_preset = ${iface.blePowerPreset}")
            }
        }
    }

    private fun yesNo(b: Boolean): String = if (b) "Yes" else "No"

    /** RNS loglevels are 0 (critical) .. 7 (extreme). */
    private fun logLevel(level: LogLevel): Int =
        when (level) {
            LogLevel.CRITICAL -> 0
            LogLevel.ERROR -> 1
            LogLevel.WARNING -> 2
            LogLevel.INFO -> 4
            LogLevel.DEBUG -> 6
            LogLevel.VERBOSE -> 7
        }
}
