package network.columba.app.rns.backend.py

import network.columba.app.rns.api.model.InterfaceConfig
import network.columba.app.rns.api.model.LogLevel
import network.columba.app.rns.api.model.ReticulumConfig

/**
 * Renders a [ReticulumConfig] into upstream RNS's on-disk `config` file
 * format. Upstream `RNS.Reticulum(configdir=...)` reads `<configdir>/config`
 * at construction; this is how the Python flavor's interfaces get wired.
 *
 * This is **backend-specific marshalling**, not app logic — the kotlin
 * backend hands the same [ReticulumConfig] to reticulum-kt's typed API
 * instead. It lives here (not in `:rns-host`) because the RNS config-file
 * grammar is a Python-RNS concept.
 *
 * Coverage: the IP-based interface types (`AutoInterface`, `TCPClient`,
 * `TCPServer`, `UDP`) render to complete, correct sections. `RNode` and
 * `AndroidBLE` render a section pointing at the bundled custom interface
 * class — but those classes also have to be *deployed* into the RNS
 * interfaces directory for `Transport.find_interfaces()` to load them; that
 * deployment step is on-device integration work (see PINNED_VERSIONS.md).
 */
internal object RnsConfigFile {
    /**
     * Build the `config` file contents for [config].
     *
     * `shareInstance` true → render `share_instance = yes` and SKIP
     * the `[interfaces]` block so RNS RPCs into an existing shared
     * instance (mirrors v0.10.x). Otherwise render `[interfaces]` with
     * the user's enabled set; AutoInterface entries get force-disabled
     * (with a `# WARNING: ...` comment) when `skipAutoInterface = true`
     * — the caller has determined the multicast bind would conflict
     * with another RNS app on the device.
     */
    fun build(
        config: ReticulumConfig,
        shareInstance: Boolean = false,
        skipAutoInterface: Boolean = false,
    ): String {
        val sb = StringBuilder()
        sb.appendLine("# Generated by :rns-backend-py — do not hand-edit.")
        sb.appendLine()
        sb.appendLine("[reticulum]")
        sb.appendLine("  enable_transport = ${yesNo(config.enableTransport)}")
        sb.appendLine("  share_instance = ${yesNo(shareInstance)}")
        if (shareInstance) sb.appendLine("  shared_instance_type = tcp")
        sb.appendLine("  shared_instance_port = 37428")
        sb.appendLine("  instance_control_port = 37429")
        // Inter-app shared-instance auth (Sideband → Connectivity → Share
        // Instance Access). Only relevant when joining; harmless to omit
        // when we're the master, so gate on shareInstance.
        if (shareInstance) {
            config.rpcKey?.takeIf { it.isNotBlank() }?.let {
                sb.appendLine("  rpc_key = $it")
            }
        }
        sb.appendLine("  panic_on_interface_error = No")
        // Interface-discovery settings (RNS 1.1.x). Upstream `RNS.Reticulum`
        // reads these from `[reticulum]` at construction (Reticulum.py:551,584)
        // — there is no live-update path, which is why the VM routes discovery
        // toggle / autoconnect slider / IFAC-only switch through a full restart
        // when `hotReloadInterfaces = false`. Emit them on every build so the
        // next-restart Reticulum() picks them up; default of `discover = no`
        // and `autoconnect = 0` mirrors upstream's own off-by-default.
        sb.appendLine("  discover_interfaces = ${yesNo(config.discoverInterfaces)}")
        sb.appendLine("  autoconnect_discovered_interfaces = ${config.autoconnectDiscoveredInterfaces}")
        sb.appendLine()
        sb.appendLine("[logging]")
        sb.appendLine("  loglevel = ${logLevel(config.logLevel)}")
        if (!shareInstance) {
            sb.appendLine()
            sb.appendLine("[interfaces]")
            config.enabledInterfaces.filter { it.enabled }.forEach { iface ->
                renderInterface(sb, iface, skipAutoInterface)
            }
        }
        return sb.toString()
    }

    private fun renderInterface(
        sb: StringBuilder,
        iface: InterfaceConfig,
        skipAutoInterface: Boolean = false,
    ) {
        sb.appendLine()
        sb.appendLine("  [[${iface.name}]]")
        when (iface) {
            is InterfaceConfig.AutoInterface -> {
                if (skipAutoInterface) {
                    sb.appendLine("    # WARNING: AutoInterface disabled at runtime because another RNS")
                    sb.appendLine("    # app on this device holds the multicast data port. Enabling it")
                    sb.appendLine("    # would crash this process with EADDRINUSE.")
                    sb.appendLine("    type = AutoInterface")
                    sb.appendLine("    enabled = no")
                    return
                }
                sb.appendLine("    type = AutoInterface")
                sb.appendLine("    enabled = yes")
                if (iface.groupId.isNotBlank()) sb.appendLine("    group_id = ${iface.groupId}")
                sb.appendLine("    discovery_scope = ${iface.discoveryScope}")
                iface.discoveryPort?.let { sb.appendLine("    discovery_port = $it") }
                iface.dataPort?.let { sb.appendLine("    data_port = $it") }
                sb.appendLine("    mode = ${iface.mode}")
            }
            is InterfaceConfig.TCPClient -> {
                sb.appendLine("    type = TCPClientInterface")
                sb.appendLine("    enabled = yes")
                sb.appendLine("    target_host = ${iface.targetHost}")
                sb.appendLine("    target_port = ${iface.targetPort}")
                if (iface.kissFraming) sb.appendLine("    kiss_framing = true")
                sb.appendLine("    mode = ${iface.mode}")
                iface.networkName?.let { sb.appendLine("    network_name = $it") }
                iface.passphrase?.let { sb.appendLine("    passphrase = $it") }
            }
            is InterfaceConfig.TCPServer -> {
                sb.appendLine("    type = TCPServerInterface")
                sb.appendLine("    enabled = yes")
                sb.appendLine("    listen_ip = ${iface.listenIp}")
                sb.appendLine("    listen_port = ${iface.listenPort}")
                sb.appendLine("    mode = ${iface.mode}")
                iface.networkName?.let { sb.appendLine("    network_name = $it") }
                iface.passphrase?.let { sb.appendLine("    passphrase = $it") }
            }
            is InterfaceConfig.UDP -> {
                sb.appendLine("    type = UDPInterface")
                sb.appendLine("    enabled = yes")
                sb.appendLine("    listen_ip = ${iface.listenIp}")
                sb.appendLine("    listen_port = ${iface.listenPort}")
                sb.appendLine("    forward_ip = ${iface.forwardIp}")
                sb.appendLine("    forward_port = ${iface.forwardPort}")
                sb.appendLine("    mode = ${iface.mode}")
            }
            is InterfaceConfig.RNode -> {
                // RNode interface emission splits by connection_mode because
                // the Python and Kotlin worlds have different paths to RNode
                // hardware:
                //
                //   • TCP — upstream RNS ships `RNS.Interfaces.Android.
                //     RNodeInterface` which natively speaks TCP to an
                //     `rnodeserver`-style bridge (hardcoded port 7633). RNS's
                //     conditional import in Reticulum.py:43 dispatches to the
                //     Android variant on android, and the variant treats
                //     `tcp_host = <ip>` as "use TCP, connect to this host on
                //     port 7633". No jnius, no Kotlin bridge needed — pure
                //     sockets. We emit `type = RNodeInterface` so RNS's
                //     internal dispatch (Reticulum.py:900) picks it up.
                //   • BLE / Classic / USB — upstream needs jnius for
                //     Bluetooth (broken under Chaquopy). We bundle a
                //     Columba-authored RNS.Interface
                //     (columba_rnode_interface.py, deployed by
                //     event_bridge.deploy_bundled_interfaces to
                //     <configdir>/interfaces/ColumbaRNodeInterface.py) that
                //     bridges via KotlinRNodeBridge / KotlinUSBBridge.
                if (iface.connectionMode == "tcp") {
                    val host = iface.tcpHost
                    if (host.isNullOrBlank()) {
                        sb.appendLine("    # TCP RNode missing tcp_host — interface skipped")
                        return
                    }
                    sb.appendLine("    type = RNodeInterface")
                    sb.appendLine("    enabled = yes")
                    sb.appendLine("    tcp_host = $host")
                    // tcp_port: upstream's Android RNodeInterface hardcodes
                    // TARGET_PORT = 7633. The UI captures iface.tcpPort but
                    // RNS will use 7633 regardless. Logged as a comment for
                    // future-reader awareness.
                    if (iface.tcpPort != 7633) {
                        sb.appendLine("    # NOTE: tcpPort=${iface.tcpPort} from UI, but upstream RNS hardcodes 7633")
                    }
                    sb.appendLine("    frequency = ${iface.frequency}")
                    sb.appendLine("    bandwidth = ${iface.bandwidth}")
                    sb.appendLine("    txpower = ${iface.txPower}")
                    sb.appendLine("    spreadingfactor = ${iface.spreadingFactor}")
                    sb.appendLine("    codingrate = ${iface.codingRate}")
                    sb.appendLine("    mode = ${iface.mode}")
                } else {
                    // BLE / Classic / USB — bundled custom interface path.
                    // ColumbaRNodeInterface bridges to KotlinRNodeBridge
                    // (BLE/Classic) and KotlinUSBBridge (USB) on the Kotlin
                    // side via event_bridge / usb_bridge slim-Python
                    // accessors. See columba_rnode_interface.py.
                    sb.appendLine("    type = ColumbaRNodeInterface")
                    sb.appendLine("    enabled = yes")
                    sb.appendLine("    connection_mode = ${iface.connectionMode}")
                    if (iface.targetDeviceName.isNotBlank()) {
                        sb.appendLine("    target_device_name = ${iface.targetDeviceName}")
                    }
                    iface.usbDeviceId?.let { sb.appendLine("    usb_device_id = $it") }
                    iface.usbVendorId?.let { sb.appendLine("    usb_vendor_id = $it") }
                    iface.usbProductId?.let { sb.appendLine("    usb_product_id = $it") }
                    sb.appendLine("    frequency = ${iface.frequency}")
                    sb.appendLine("    bandwidth = ${iface.bandwidth}")
                    sb.appendLine("    txpower = ${iface.txPower}")
                    sb.appendLine("    spreadingfactor = ${iface.spreadingFactor}")
                    sb.appendLine("    codingrate = ${iface.codingRate}")
                    iface.stAlock?.let { sb.appendLine("    st_alock = $it") }
                    iface.ltAlock?.let { sb.appendLine("    lt_alock = $it") }
                    sb.appendLine("    mode = ${iface.mode}")
                    if (iface.enableFramebuffer) sb.appendLine("    enable_framebuffer = yes")
                    iface.networkName?.let { sb.appendLine("    network_name = $it") }
                    iface.passphrase?.let { sb.appendLine("    passphrase = $it") }
                }
            }
            is InterfaceConfig.AndroidBLE -> {
                // Bundled custom interface (ble_modules/android_ble_interface.py
                // → AndroidBLEInterface). RNS Transport.find_interfaces() loads
                // <configdir>/interfaces/<type>.py and then instantiates the
                // matching class — `type = AndroidBLE` resolves to AndroidBLE.py
                // which contains `class AndroidBLEInterface(BLEInterface)`.
                // event_bridge.deploy_bundled_interfaces() writes the file.
                sb.appendLine("    type = AndroidBLE")
                sb.appendLine("    enabled = yes")
                if (iface.deviceName.isNotBlank()) {
                    sb.appendLine("    device_name = ${iface.deviceName}")
                }
                // Parent BLEInterface reads `max_connections`, not `max_peers`.
                sb.appendLine("    max_connections = ${iface.maxConnections}")
                sb.appendLine("    mode = ${iface.mode}")
                sb.appendLine("    ble_power_preset = ${iface.blePowerPreset}")
                sb.appendLine("    ble_discovery_interval_ms = ${iface.bleDiscoveryIntervalMs}")
                sb.appendLine("    ble_discovery_interval_idle_ms = ${iface.bleDiscoveryIntervalIdleMs}")
                sb.appendLine("    ble_scan_duration_ms = ${iface.bleScanDurationMs}")
                sb.appendLine("    ble_advertising_refresh_interval_ms = ${iface.bleAdvertisingRefreshIntervalMs}")
            }
        }
    }

    private fun yesNo(b: Boolean): String = if (b) "Yes" else "No"

    /** RNS loglevels are 0 (critical) .. 7 (extreme). */
    private fun logLevel(level: LogLevel): Int =
        when (level) {
            LogLevel.CRITICAL -> 0
            LogLevel.ERROR -> 1
            LogLevel.WARNING -> 2
            LogLevel.INFO -> 4
            LogLevel.DEBUG -> 6
            LogLevel.VERBOSE -> 7
        }
}
