package network.columba.app.ui.screens

import android.app.Application
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import network.columba.app.test.RegisterComponentActivityRule
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.RuleChain
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Unit tests for ProfileIconCard in MyIdentityScreen.
 * Tests the profile icon customization UI section using the actual production component.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34], application = Application::class)
class MyIdentityScreenProfileIconTest {
    private val registerActivityRule = RegisterComponentActivityRule()
    private val composeRule = createComposeRule()

    @get:Rule
    val ruleChain: RuleChain = RuleChain.outerRule(registerActivityRule).around(composeRule)

    val composeTestRule get() = composeRule

    // ========== Display Tests ==========

    @Test
    fun profileIconCard_displaysTitle() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = null,
                foregroundColor = null,
                backgroundColor = null,
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        composeTestRule.onNodeWithText("Profile Icon").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_displaysDescription() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = null,
                foregroundColor = null,
                backgroundColor = null,
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        composeTestRule.onNodeWithText(
            "Customize your profile icon that others will see. " +
                "This is compatible with Sideband and other Reticulum apps.",
        ).assertIsDisplayed()
    }

    @Test
    fun profileIconCard_displaysChooseCustomIconButton_whenNoIcon() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = null,
                foregroundColor = null,
                backgroundColor = null,
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        composeTestRule.onNodeWithText("Choose Custom Icon").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_displaysChangeIconButton_whenIconSet() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = "account",
                foregroundColor = "FFFFFF",
                backgroundColor = "1E88E5",
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        composeTestRule.onNodeWithText("Change Icon").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_displaysUsingIdenticon_whenNoIcon() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = null,
                foregroundColor = null,
                backgroundColor = null,
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        composeTestRule.onNodeWithText("Using Identicon").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_displaysCustomIconName_whenIconSet() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = "account",
                foregroundColor = "FFFFFF",
                backgroundColor = "1E88E5",
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        composeTestRule.onNodeWithText("Custom Icon: account").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_displaysAutoGeneratedText_whenNoIcon() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = null,
                foregroundColor = null,
                backgroundColor = null,
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        composeTestRule.onNodeWithText("Auto-generated from your identity").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_displaysTapToChangeText_whenIconSet() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = "star",
                foregroundColor = "FF0000",
                backgroundColor = "0000FF",
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        composeTestRule.onNodeWithText("Tap to change your custom icon").assertIsDisplayed()
    }

    // ========== Callback Tests ==========

    @Test
    fun profileIconCard_chooseCustomIconButtonCallsOnEditIcon() {
        var editCalled = false

        composeTestRule.setContent {
            ProfileIconCard(
                iconName = null,
                foregroundColor = null,
                backgroundColor = null,
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = { editCalled = true },
            )
        }

        composeTestRule.onNodeWithText("Choose Custom Icon").performClick()
        assertTrue("onEditIcon should be called", editCalled)
    }

    @Test
    fun profileIconCard_changeIconButtonCallsOnEditIcon() {
        var editCalled = false

        composeTestRule.setContent {
            ProfileIconCard(
                iconName = "star",
                foregroundColor = "FF0000",
                backgroundColor = "0000FF",
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = { editCalled = true },
            )
        }

        composeTestRule.onNodeWithText("Change Icon").performClick()
        assertTrue("onEditIcon should be called", editCalled)
    }

    // ========== Icon Display Tests ==========

    @Test
    fun profileIconCard_showsIdenticon_whenNoIconSet() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = null,
                foregroundColor = null,
                backgroundColor = null,
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        // Card should render without crashing when using identicon fallback
        composeTestRule.onNodeWithText("Profile Icon").assertIsDisplayed()
        composeTestRule.onNodeWithText("Using Identicon").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_showsProfileIcon_whenIconSet() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = "account",
                foregroundColor = "FFFFFF",
                backgroundColor = "1E88E5",
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        // Card should render without crashing when showing profile icon
        composeTestRule.onNodeWithText("Profile Icon").assertIsDisplayed()
        composeTestRule.onNodeWithText("Custom Icon: account").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_handlesEmptyFallbackHash() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = null,
                foregroundColor = null,
                backgroundColor = null,
                fallbackHash = ByteArray(0),
                onEditIcon = {},
            )
        }

        // Should not crash with empty hash
        composeTestRule.onNodeWithText("Profile Icon").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_handlesPartialIconData() {
        // Only icon name provided, missing colors - shows identicon but displays custom icon info
        // because the display text is based on whether iconName is set
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = "account",
                foregroundColor = null,
                backgroundColor = null,
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        // Since iconName is set (even if colors are missing), shows custom icon text
        // The actual display falls back to identicon but UX shows custom icon info
        composeTestRule.onNodeWithText("Custom Icon: account").assertIsDisplayed()
        composeTestRule.onNodeWithText("Change Icon").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_handlesSpecialCharactersInIconName() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = "account-circle-outline",
                foregroundColor = "FFFFFF",
                backgroundColor = "1E88E5",
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        composeTestRule.onNodeWithText("Custom Icon: account-circle-outline").assertIsDisplayed()
    }

    @Test
    fun profileIconCard_handlesLongIconName() {
        composeTestRule.setContent {
            ProfileIconCard(
                iconName = "emoticon-happy-outline",
                foregroundColor = "FFFFFF",
                backgroundColor = "1E88E5",
                fallbackHash = ByteArray(16) { it.toByte() },
                onEditIcon = {},
            )
        }

        composeTestRule.onNodeWithText("Custom Icon: emoticon-happy-outline").assertIsDisplayed()
    }
}
